// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID         int64
	FirstName  string
	LastName   string
	Email      string
	Address1   sql.NullString
	Address2   sql.NullString
	PostalCode string
}

type Order struct {
	ID         int64
	CustomerID int64
	RegionID   int64
	OrderDate  time.Time
	Status     string
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	ProductID int64
	Quantity  int64
}

type Product struct {
	ID          int64
	ProductName string
	Price       float64
}

type Region struct {
	ID           int64
	RegionName   string
	ShippingRate float64
}
