// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, region_id, order_date, status)
VALUES (
    ?,
    ?,
    ?,
    ?
)
RETURNING id, customer_id, region_id, order_date, status
`

type CreateOrderParams struct {
	CustomerID int64
	RegionID   int64
	OrderDate  time.Time
	Status     string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.CustomerID,
		arg.RegionID,
		arg.OrderDate,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RegionID,
		&i.OrderDate,
		&i.Status,
	)
	return i, err
}
