// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regions.sql

package database

import (
	"context"
)

const getRegionByName = `-- name: GetRegionByName :one
SELECT id, region_name, shipping_rate FROM regions
WHERE region_name = ?
`

func (q *Queries) GetRegionByName(ctx context.Context, regionName string) (Region, error) {
	row := q.db.QueryRowContext(ctx, getRegionByName, regionName)
	var i Region
	err := row.Scan(&i.ID, &i.RegionName, &i.ShippingRate)
	return i, err
}
